name: Deploy to mirror repos

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Deploy to jaydes.fr
       run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    rm -rf temp-jaydes.fr       # supprime l'ancien dossier s'il existe
    git clone --recurse-submodules=false https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/YazWare/jaydes.fr.git temp-jaydes.fr
    shopt -s extglob
    cp -r !(temp-jaydes.fr|.github) temp-jaydes.fr/
    cd temp-jaydes.fr
    git add .
    git diff-index --quiet HEAD || git commit -m "Sync from yeni.store"
    git push

      - name: Deploy to jaydes.store
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/YazWare/jaydes.store.git temp-jaydes.store
          shopt -s extglob
          cp -r !(temp-jaydes.store|.github|CNAME) temp-jaydes.store/
          cd temp-jaydes.store
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync from yeni.store"
          git push
