name: Deploy to mirror repos

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          submodules: false   # <-- IMPORTANT

      - name: Deploy to jaydes.fr
        run: |
          set -e
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          rm -rf temp
          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/YazWare/jaydes.fr.git temp
          
          shopt -s extglob
          cp -r !(temp|.github|CNAME) temp/
          
          cd temp
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync from yeni.store"
          git push

      - name: Deploy to jaydes.store
        run: |
          set -e
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          rm -rf temp
          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/YazWare/jaydes.store.git temp
          
          shopt -s extglob
          cp -r !(temp|.github|CNAME) temp/
          
          cd temp
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync from yeni.store"
          git push
